# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 关于我
    url: /
    weight: 10
  - name: 科研经历
    url: experience/
    weight: 20
  - name: 个人项目
    url: projects/
    weight: 30
  - name: 技术博客
    url: post/
    weight: 40
